const IMAGES = {
	ACCOUNT: require('./images/accounts.png'),
	AVATAR: require('./images/avatar.png'),
	BACK: require('./images/back.png'),
	BURGER_MENU_ICON: require('./images/burgerMenuIcon.png'),
	CARDS: require('./images/cards.png'),
	CIRCLE_BUTTON_CHECKING: require('./images/circleButtonChecking.png'),
	CIRCLE_BUTTON_PAY: require('./images/circleButtonPay.png'),
	CIRCLE_BUTTON_SEND: require('./images/circleButtonSend.png'),
	CONFETTI2: require('./images/confetti2.png'),
	GIVING: require('./images/giving.png'),
	HEART: require('./images/heart.png'),
	HOME: require('./images/home.png'),
	LOGO_SPLASH_SCREEN: require('./images/logo_splash_screen.png'),
	LOGO: require('./images/logo.png'),
	OVAL: require('./images/oval.png'),
	PAYMENT: require('./images/payment.png'),
	PLAY: require('./images/play.png'),
	RECTANGLE: require('./images/rectangle.png'),
	RECTANGLE2: require('./images/rectangle2.png'),
	SAVINGS_GRAPH_V2: require('./images/savingsGraphV2.png'),
	SHARE_ARROW: require('./images/shareArrow.png'),
	TOM_LEGEND: require('./images/TOM-Legend.png'),
	TOM: require('./images/TOM.png'),
}

export default IMAGES;
